version: '3.8'
services:
  api-bubble-harmonika:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: metro.proxy.rlwy.net
      DB_USER: postgres
      DB_PASSWORD: dUKXDkkboJVzyOLRnkyRKdGnauflQdXy
      DB_NAME: railway
      DB_PORT: 26668
      PORT: :3000
      MIGRATE: false
      SCHEMA: harmonika
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - api-bubble-harmonika-network

  postgres:
    image: postgres
    ports:
      - "9999:9999"
    networks:
      - api-bubble-harmonika-network
